services:
  client:
    platform: linux/amd64
    image: social-login-proto-client
    container_name: client
    build:
      context: client/src
      dockerfile: ../Dockerfile
    ports:
      - 0.0.0.0:8000:3000
    env_file:
      - ./client/.env.local
    volumes:
      - ./client/src:/src
    command: npm run dev
  server1:
    platform: linux/amd64
    image: social-login-proto-server1
    container_name: server1
    build:
      context: server/src
      dockerfile: ../Dockerfile
    ports:
      - 0.0.0.0:7778:3000
    env_file:
      - ./server/.env.local
    volumes:
      - ./server/src:/src
    command: npm run start
  server2:
    platform: linux/amd64
    image: social-login-proto-server2
    container_name: server2
    build:
      context: server/src
      dockerfile: ../Dockerfile
    ports:
      - 0.0.0.0:7779:3000
    env_file:
      - ./server/.env.local
    volumes:
      - ./server/src:/src
    command: npm run start
  proxy:
    platform: linux/amd64
    image: nginx:1.26-bookworm
    container_name: proxy
    volumes:
      - ./proxy/certificates/:/etc/nginx/certificates/
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 0.0.0.0:7777:443
  redis:
    image: redis:7.4-bookworm
    platform: linux/amd64
    container_name: redis
    ports:
      - 0.0.0.0:6379:6379
  redisinsight:
    image: redislabs/redisinsight:2.66
    platform: linux/amd64
    container_name: redisinsight
    ports:
      - 0.0.0.0:5540:5540
    volumes:
      - ./redis/insight:/data
